version: '3.7'

services:
  front:
    image: nginx
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/proxy.conf:/etc/nginx/proxy.conf:ro
    command: [nginx, '-g', 'daemon off;']
    ports:
      - "8000:80"
    depends_on:
      - api
      - webui
    networks:
      - nginxnet

  webui:
    build:
      context: webui
    networks:
      nginxnet:
        aliases:
          - web

  api:
    image: alerta/alerta-web  # use API in "alerta-web" image
    depends_on:
      - db
    volumes:
      - ./api/alertad.conf:/app/alertad.conf
    environment:
      - DEBUG=1  # remove this line to turn DEBUG off
      - DATABASE_URL=postgres://postgres:postgres@db:5432/monitoring
      - AUTH_REQUIRED=True
      - ADMIN_USERS=admin@alerta.io,devops@alerta.io #default password: alerta
      - ADMIN_KEY=demo-key  # assigned to first user in ADMIN_USERS list
      # - PLUGINS=reject,blackout,normalise,enhance
    networks:
      nginxnet:
        aliases:
          - api

  db:
    image: postgres
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=monitoring
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      nginxnet:
        aliases:
          - db
    restart: always

networks:
  nginxnet: {}
