version: '3.7'

services:
  proxy:
    image: httpd:2.4
    volumes:
      - ./proxy/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./proxy/proxy.conf:/usr/local/apache2/conf/extra/proxy.conf:ro
    ports:
      - "8000:80"   # HTTP port
    depends_on:
      - api
      - webui
    networks:
      - net

  webui:
    build:
      context: webui
    networks:
      net:
        aliases:
          - web

  api:
    image: alerta/alerta-web  # use API in "alerta-web" image
    depends_on:
      - db
    volumes:
      - ./api/alertad.conf:/app/alertad.conf
    environment:
      - DEBUG=1  # remove this line to turn DEBUG off
      - DATABASE_URL=postgres://postgres:postgres@db:5432/monitoring
      - AUTH_REQUIRED=True
      - ADMIN_USERS=admin@alerta.io,devops@alerta.io #default password: alerta
      - ADMIN_KEY=demo-key  # assigned to first user in ADMIN_USERS list
      # - PLUGINS=reject,blackout,normalise,enhance
    networks:
      net:
        aliases:
          - api

  db:
    image: postgres
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=monitoring
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      net:
        aliases:
          - db
    restart: always

networks:
  net: {}
