version: '3'

services:
  alerta:
    image: alerta/alerta-web
    container_name: alerta-web
    volumes:
      - $PWD/config/alertad.conf:/app/alertad.conf
    ports:
      - 8000:8080
    depends_on:
      - db
      - keycloak
    environment:
      - DEBUG=1  # remove this line to turn DEBUG off
      - DATABASE_URL=postgres://postgres:postgres@db:5432/monitoring
      - AUTH_REQUIRED=True
      - ADMIN_USERS=alice  # password=alice
      - AUTH_PROVIDER=keycloak
      - KEYCLOAK_URL=http://host.docker.internal:8080
      - KEYCLOAK_REALM=demo
      # - ALLOWED_OIDC_ROLES=devops
      # - ALLOWED_EMAIL_DOMAINS=alerta.io,alerta.dev
      - OAUTH2_CLIENT_ID=alerta-webui
      - OAUTH2_CLIENT_SECRET=fa134126-222b-4fc3-a8dd-070a28f39e88
    restart: always
  db:
    image: postgres
    container_name: alerta-db
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: monitoring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always

  keycloak:
      image: jboss/keycloak
      container_name: keycloak
      volumes:
        - $PWD/config/demo-realm.json:/tmp/demo-realm.json
      environment:
        DB_VENDOR: h2
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        KEYCLOAK_IMPORT: /tmp/demo-realm.json
        # JDBC_PARAMS: "ssl=true"
      ports:
        - 8080:8080
